version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
      python: latest
    commands:
      - npm install -g aws-cdk
      - pip3 install -r requirements.txt
  build:
    commands:
      - make