version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
      python: latest
    commands:
      - npm install -g aws-cdk
      - pip3 install -r requirements.txt
  pre_build:
    commands:
      - make lint
  build:
    commands:
      - make deploy
      - make publish
  post_build:
    commands:
      - make sync
      - make invalidate