baseURL: "https://how.wtf/"
copyright: "© 2021-2024 how.wtf"
enableRobotsTXT: true
languageCode: en-us
relativeURLs: true
title: how.wtf
theme: bearcub
uglyurls: true

author:
  name: Thomas Taylor

markup:
  highlight:
    lineNos: true
    lineNumbersInTable: false
    noClasses: false

params:
  dateFormat: 2006-01-02
  description: |
    Helpful posts on programming, cloud infrastructure, AI, and other software engineering topics to help with your "WTF?!" moments.

    Written by Thomas Taylor, an AWS Community Builder.
  favicon: images/favicon.ico
  goatcounter: "https://stats.how.wtf/count"
  googleSiteVerification: "ZugdoUg37QGKjGLpsGOxAdNXmNot5mL5osXhvnAeWqA"
  generateSocialCard: false
  images:
  - images/8yRnin.webp
  latestPostsCount: 8
  social:
    email: thomas@how.wtf
    twitter: imthomastaylor
  links:
  - name: PERSONAL
    url: "https://thomasgtaylor.com"
    description: Visit my personal website
  - name: EMAIL
    url: "mailto:thomas@how.wtf"
    description: Send me an email
  title: how.wtf

menus:
  main:
  - name: Newsletter 
    weight: 3
    url: https://weeklywtf.beehiiv.com/subscribe?utm_source=howwtf&utm_medium=organic
  - name: RSS
    weight: 4
    url: /index.xml


permalinks:
  page:
    blog: :title
  section:
    blog: /posts

sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5
